version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/ruby:3.0.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/blankpages1/SoftwareEngineeringProject/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          bundle install
          bundle exec rake db:migrate RAILS_ENV=test
          bundle exec rspec

workflows:
  my-custom-workflow:
    jobs:
      - build