version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/ruby:3.0.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/blankpages1/SoftwareEngineeringProject/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          brew install sqlite3
          bundle install --without production
          bundle exec rake db:migrate
          bundle exec rspec

workflows:
  my-custom-workflow:
    jobs:
      - build